export const CLONE_PROTOCOLS = {
  HTTPS: 'HTTPS',
  SSH: 'SSH'
};

export const RUNTIME_MESSAGES = {
  CLONE_IN_TOOL: 'CLONE_IN_TOOL',
  DISABLE_PAGE_ACTION: 'DISABLE_PAGE_ACTION',
  ENABLE_PAGE_ACTION: 'ENABLE_PAGE_ACTION',
  GET_PROTOCOL: 'GET_PROTOCOL',
  GET_TOOLS: 'GET_TOOLS',
  NAVIGATE_IN_TOOL: 'NAVIGATE_IN_TOOL',
  SAVE_PROTOCOL: 'SAVE_PROTOCOL'
};

export const TOOLBOX_ERRORS = {
  COMMUNICATION_ERROR: 'COMMUNICATION_ERROR',
  TOOLS_NOT_FOUND: 'TOOLS_NOT_FOUND'
};
